spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/tfa
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver

clickatell:
  username: wedonegood
  password: SVacUSMNUCYXee
  api-id: 3630933
