# General properties
server:
  port: 8087


folder:
  home: /opt/hrtool/
  uploads: uploads/
  profile:
    picture: profilePicture/
  passport:
    scan: passportScan/
  

file:
  name:
    profile:
      picture: profilePicture
    passport:
      scan: passportScan
    small: small
    medium: medium
    big: big
    preview: preview
    cities: cities.json
    countries: countries.json
    
  size:
    small: 44
    medium: 56
    big: 138
    passport: 99