# General properties
server:
  port: 8087


uploads:
  folder: uploads/

file:
  name:
    profile:
      picture: profilePicture
    passport:
      scan: passportScan
    small: small
    big: big
    preview: preview
    
  size:
    small: 44
    big: 138
    passport: 99